"""add_source_content_to_courses

Revision ID: 6165ad326b3d
Revises: c9250c655196
Create Date: 2025-12-09 01:04:09.361214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6165ad326b3d'
down_revision: Union[str, None] = 'c9250c655196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('source_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'source_content')
    # ### end Alembic commands ###
