"""add_username_to_users

Revision ID: c9250c655196
Revises: 34b0a3916e57
Create Date: 2025-12-08 20:27:22.917797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9250c655196'
down_revision: Union[str, None] = '34b0a3916e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar columna como nullable primero
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    
    # Generar usernames para usuarios existentes basados en su email
    op.execute("UPDATE users SET username = LOWER(SPLIT_PART(email, '@', 1) || '_' || id) WHERE username IS NULL")
    
    # Hacer la columna NOT NULL
    op.alter_column('users', 'username', nullable=False)
    
    # Crear índice único
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
